version: '3.7'
services:
    qb-app:
        container_name: qb-app
        build: ./ 
        ports:
            - "8080:8080"
        labels:
            NAME: "qb-app"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge